#!/bin/sh

# ACVERSION="-1.10"
ACLOCAL=aclocal${ACVERSION}
AUTOMAKE=automake${ACVERSION}
AUTOHEADER=autoheader
AUTOCONF=autoconf
GLIBTOOLIZE=libtoolize

# LISTCMDVER="${ACLOCAL} ${AUTOMAKE} ${AUTOHEADER} ${AUTOCONF} ${GLIBTOOLIZE}"
# for C in ${LISTCMDVER}; do
  # echo ${C}
  # ${C} --version
# done

# ${GLIBTOOLIZE} --force --copy || exit
${GLIBTOOLIZE} --copy || exit

${AUTOHEADER} || exit

${ACLOCAL} || exit

# ${AUTOMAKE} --gnu --add-missing --force-missing  || exit
${AUTOMAKE} --copy --add-missing --force-missing  || exit
# ${AUTOMAKE} -a -c || exit
# ${AUTOMAKE} -a || exit

${AUTOCONF} || exit

