#!/bin/sh

# Syntax: cmd
# 
# Dependencies: bash, nmxp_sds.sh
#
# TODO: input parameters
#
# Author: Matteo Quintiliani - quintiliani@ingv.it - I.N.G.V.
#

STATION_LIST="IV.ACER.HLE IV.ACER.HLN IV.ACER.HLZ IV.ARCI.HLE IV.ARCI.HLN IV.ARCI.HLZ IV.ASQU.HLE IV.ASQU.HLN IV.ASQU.HLZ IV.BDI.HLE  IV.BDI.HLN  IV.BDI.HLZ  IV.BOB.HLE  IV.BOB.HLN  IV.BOB.HLZ  IV.BSSO.HLE IV.BSSO.HLN IV.BSSO.HLZ IV.BULG.HLE IV.BULG.HLN IV.BULG.HLZ IV.CAFE.HLE IV.CAFE.HLN IV.CAFE.HLZ IV.CAFI.HLE IV.CAFI.HLN IV.CAFI.HLZ IV.CAFR.HLE IV.CAFR.HLN IV.CAFR.HLZ IV.CARO.HLE IV.CARO.HLN IV.CARO.HLZ IV.CASP.HLE IV.CASP.HLN IV.CASP.HLZ IV.CERA.HLE IV.CERA.HLN IV.CERA.HLZ IV.CRMI.HLE IV.CRMI.HLN IV.CRMI.HLZ IV.GROG.HLE IV.GROG.HLN IV.GROG.HLZ IV.LATE.HLE IV.LATE.HLN IV.LATE.HLZ IV.LSD.HLE  IV.LSD.HLN  IV.LSD.HLZ  IV.MAON.HLE IV.MAON.HLN IV.MAON.HLZ IV.MCEL.HLE IV.MCEL.HLN IV.MCEL.HLZ IV.MDI.HLE  IV.MDI.HLN  IV.MDI.HLZ  IV.MIDA.HLE IV.MIDA.HLN IV.MIDA.HLZ IV.MIGL.HLE IV.MIGL.HLN IV.MIGL.HLZ IV.MOCO.HLE IV.MOCO.HLN IV.MOCO.HLZ IV.MODR.HLE IV.MODR.HLN IV.MODR.HLZ IV.MONC.HLE IV.MONC.HLN IV.MONC.HLZ IV.MRB1.HLE IV.MRB1.HLN IV.MRB1.HLZ IV.MRGE.HLE IV.MRGE.HLN IV.MRGE.HLZ IV.MRLC.HLE IV.MRLC.HLN IV.MRLC.HLZ IV.MSAG.HLE IV.MSAG.HLN IV.MSAG.HLZ IV.MTRZ.HLE IV.MTRZ.HLN IV.MTRZ.HLZ IV.MTSN.HLE IV.MTSN.HLN IV.MTSN.HLZ IV.MURB.HLE IV.MURB.HLN IV.MURB.HLZ IV.PALZ.HLE IV.PALZ.HLN IV.PALZ.HLZ IV.POFI.HLE IV.POFI.HLN IV.POFI.HLZ IV.PSB1.HLE IV.PSB1.HLN IV.PSB1.HLZ IV.PTRJ.HLE IV.PTRJ.HLN IV.PTRJ.HLZ IV.RNI2.HLE IV.RNI2.HLN IV.RNI2.HLZ IV.ROM9.HLE IV.ROM9.HLN IV.ROM9.HLZ IV.RSP.HLE  IV.RSP.HLN  IV.RSP.HLZ  IV.SACR.HLE IV.SACR.HLN IV.SACR.HLZ IV.SACS.HLE IV.SACS.HLN IV.SACS.HLZ IV.SALO.HLE IV.SALO.HLN IV.SALO.HLZ IV.SGRT.HLE IV.SGRT.HLN IV.SGRT.HLZ IV.SGTA.HLE IV.SGTA.HLN IV.SGTA.HLZ IV.SIRI.HLE IV.SIRI.HLN IV.SIRI.HLZ IV.SNAL.HLE IV.SNAL.HLN IV.SNAL.HLZ IV.TOLF.HLE IV.TOLF.HLN IV.TOLF.HLZ IV.TRIV.HLE IV.TRIV.HLN IV.TRIV.HLZ IV.TRTR.HLE IV.TRTR.HLN IV.TRTR.HLZ IV.VAGA.HLE IV.VAGA.HLN IV.VAGA.HLZ IV.VULT.HLE IV.VULT.HLN IV.VULT.HLZ"

# variables dependent on the input parameters
YEAR=2008
JDAYSTART=1
JDAYEND=58
OVERRIDE=y

NMXP_SDS=`dirname $0`/nmxp_sds.sh 

JDAY=${JDAYSTART}
while [ $JDAY -le ${JDAYEND} ]; do
	echo "Download for year/jday ${YEAR}.${JDAY}"
	for STATION in ${STATION_LIST}; do
		NET=`echo ${STATION} | cut -f 1 -d'.'`
		STA=`echo ${STATION} | cut -f 2 -d'.'`
		CHAN=`echo ${STATION} | cut -f 3 -d'.'`
		${NMXP_SDS} ${YEAR} ${NET} ${STA} ${CHAN} ${JDAY} ${OVERRIDE}
	done
	JDAY=$(($JDAY + 1))
done
